# Site settings
title: Super Cool Dynasty League
description: The Official Website of the SCDL.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  teams:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: teams
    values:
      layout: teampage

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - gulpfile.js
  - .gitignore
  - .babelrc
